//@/lib/ListEmul.tsx
export const listEmul = [
    { url: "/rituels//Emulation/app/ouverture", link: "Ouverture" },
    { url: "/rituels//Emulation/app/initiation", link: "Initiation" },
    { url: "/rituels//Emulation/app/initiation2", link: "Initiation-2" },
    { url: "/rituels//Emulation/app/initiation3", link: "Initiation-3" },
    { url: "/rituels//Emulation/app/plancheapp", link: "Planche tracé du 1er Grade" },
    { url: "/rituels//Emulation/app/examapp", link: "examen de passage" },
    { url: "/rituels//Emulation/cp/cpouverture", link: "Ouverture au 2ème Grade" },
    { url: "/rituels//Emulation/cp/passage", link: "Passage" },
    { url: "/rituels//Emulation/cp/planchecp", link: "Planche tracé du 2ème grade" },
    { url: "/rituels//Emulation/cp/examcp", link: "Examen d'élévation" },
    { url: "/rituels//Emulation/m/mouverture", link: "Ouverture au 3ème Grade" },
    { url: "/rituels//Emulation/m/elevation", link: "Elevation" },
    { url: "/rituels//Emulation/m/histoire", link: "histoire traditionnelle" },
    { url: "/rituels//Emulation/m/planchem", link: "planche tracé du 3ème Grade" },
    { url: "/rituels//Emulation/m/mfermeture", link: "Fermeture du 3ème Grade" },
    { url: "/rituels//Emulation/cp/cpfermeture", link: "Fermeture du 2ème Grade" },
    { url: "/rituels//Emulation/app/fermeture", link: "Fermeture de la loge" },
    { url: "/rituels//Emulation/app/chaine", link: "Chaine Emulation" },
    { url: "/rituels//Emulation/m/instalation", link: "L'instalation" },
    { url: "/rituels//Emulation/m/iexhortations", link: "Exhortations" },
    { url: "/rituels//Emulation/app/annex", link: "Annex" },
    { url: "/rituels//Emulation/app/table", link: "Travaux de table" },
  ];