export const listKT = [
    { url: "/rituels//KT/intro", link: "Introduction" },
    { url: "/rituels//KT/prepa", link: "Mise en place de la chapelle" },
    { url: "/rituels//KT/ochapitre", link: "Ouverture du chapitre" },
    { url: "/rituels//KT/rituel", link: "Elements ritueliques" },
    { url: "/rituels//KT/armement1", link: "Armement-1" },
    { url: "/rituels//KT/obligation", link: "Obligation" },
    { url: "/rituels//KT/armement12", link: "Armement-1 suite" },
    { url: "/rituels//KT/armement2", link: "Armement-2" },
    { url: "/rituels//KT/fchapitre", link: "Fermeture du chapitre" },
    { url: "/rituels//KT/diplome", link: "Remise du diplome" },
    { url: "/rituels//KT/newprecepteur", link: "Instalation du Précepteur" },
    { url: "/rituels//KT/instalation", link: "Instalation des officiers" },
    { url: "/rituels//KT/exhortation", link: "Exhortation après l'instalation" },
    { url: "/rituels//KT/epee", link: "Maniement de l'épée" },
    { url: "/rituels//KT/banquet", link: "Protocoledes banquets" },
    { url: "/rituels//KT/annex", link: "Musique et schema" },    
    ];